### ISSUE TITLE
docker-compose setup

### ISSUE THREAD

**Issue by wallaby-gopher** [micha37-martins/S.M.A.R.T-disk-monitoring-for-Prometheus#35]
Hello, I suspect I may have set up docker-compose incorrectly because Prometheus doesn't seem to be getting smartmon info. Could it be a port issue? Node_export works perfectly.
The only smartmon log is 'No log line matching the '' filter'
Here is the only error I can find, from grafana:
```
TypeError: H.toFixed is not a function

f@http://arch:3000/public/build/322.177b4bb01c5d74f9b28f.js:31:13887
div
div
i@http://arch:3000/public/build/322.177b4bb01c5d74f9b28f.js:104:90136
P@http://arch:3000/public/build/322.177b4bb01c5d74f9b28f.js:2473:38615
r@http://arch:3000/public/build/322.177b4bb01c5d74f9b28f.js:1:526
g@http://arch:3000/public/build/322.177b4bb01c5d74f9b28f.js:12:133441
i@http://arch:3000/public/build/322.177b4bb01c5d74f9b28f.js:12:133950
div
section
S@http://arch:3000/public/build/322.177b4bb01c5d74f9b28f.js:32:26261
div
div
h0@http://arch:3000/public/build/1518.a3f1f690c084a37f01c7.js:39:316089
Jt@http://arch:3000/public/build/1518.a3f1f690c084a37f01c7.js:39:138760
41507/</this.Component@http://arch:3000/public/build/322.177b4bb01c5d74f9b28f.js:278:32291
```
It continues on like that for a while.

Docker compose:
```
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  smartmon-data:
    driver: local
services:
  prometheus:
    image: docker.io/prom/prometheus:v2.55.1
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - /media/server/server/health/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana-oss:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

smartmon:
    image: ghcr.io/micha37-martins/smartmon:latest
    volumes:
      - smartmon-data:/var/lib/node_exporter/textfile_collector
    container_name: smartmon
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
    ports:
        - 9200:9200 #I chose this randomly
    restart: unless-stopped

```

Here is prometheus.yaml

```
global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

 #Example job for smartmon
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'smartmon'
    static_configs:
      - targets: ['smartmon:9200']
```

**Comment by DesertCookie** [comment]
Having the same issue.

**Comment by clementduveau** [comment]
Just a noob on this but how is your Prometheus container supposed to read the results here ? I thought smart was printing results in a file rather than exposing a Prom endpoint.

**Comment by wallaby-gopher** [comment]
> Just a noob on this but how is your Prometheus container supposed to read the results here ? I thought smart was printing results in a file rather than exposing a Prom endpoint.

Full transparency, also a noob here. I think you're onto something. I'd sorta skipped past the textfile stuff because I though it was for running locally. I don't quite know how to get the location because it's in a docker volume.

![Image](https://github.com/user-attachments/assets/b881e23a-132a-4742-826e-bee8531f8532)

So I tried changing the smartmon exporter job by adding this:

```
  - job_name: 'smartmon'
    static_configs:
      - targets: ['smartmon:9200']
      - collector.textfile.directory /media/server/docker/volumes/health_smartmon-data/_data:/var/lib/node_exporter/textfile_collector
```

but that broke prometheus entirely

```
err="parsing YAML file /etc/prometheus/prometheus.yaml: yaml: unmarshal errors:\n  line 32: cannot unmarshal !!str `collect...` into struct { Targets []string \"yaml:\\\"targets\\\"\"; Labels model.LabelSet \"yaml:\\\"labels\\\"\" }"
```

how else would the node access the file smartmon is making?

**Comment by clementduveau** [comment]
Check node_exporter doc. It's with a flag --collector.textfile.directory

**Comment by wallaby-gopher** [comment]
> Check node_exporter doc. It's with a flag --collector.textfile.directory

If you see above I tried adding

```
- collector.textfile.directory /media/server/docker/volumes/health_smartmon-data/_data:/var/lib/node_exporter/textfile_collector
```
I forgot I just need to add the docker volume to the node_exporter too.
Here you can see me verifying it has access to the same file

![Image](https://github.com/user-attachments/assets/a5135933-a350-4e58-a786-5f72b19bcd92)

problem is it's just a prom and prometheus throws an error when I have it like this so I think either there is a prom endpoint after all or I just don't know how to add the directory to node_config.

```
ts=2025-03-27T17:00:31.165Z caller=main.go:575 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yaml)" file=/etc/prometheus/prometheus.yaml err="parsing YAML file /etc/prometheus/prometheus.yaml: yaml: unmarshal errors:\n  line 32: cannot unmarshal !!str `collect...` into struct { Targets []string \"yaml:\\\"targets\\\"\"; Labels model.LabelSet \"yaml:\\\"labels\\\"\" }"
```

**Comment by clementduveau** [comment]
Error is self-explanatory: line 32 is incorrect. Ask an LLM how to configure the textfile collector. You don't need to setup a scrape job.

**Comment by wallaby-gopher** [comment]
> Error is self-explanatory: line 32 is incorrect. Ask an LLM how to configure the textfile collector. You don't need to setup a scrape job.

LLM was talking nonsense, but I found somewhere else you can input it as a command so node exporter now has
```
command:
      - "--path.rootfs=/host"
      - '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector'
  ```
I also removed the scrape job as suggested, unfortunately, no changes in behavior.
Finally I was messing around and saw smartctl didn't work in the container. I had to add privileged: true to SMART because even with devices it wasn't successfully reading them. Thanks for your help!

@DesertCookie let me know if you're still stuck after adding these.

![Image](https://github.com/user-attachments/assets/a8bee0e5-c478-4af4-8655-7d11ae8446d7)

**Comment by alexey-sh** [comment]
I have installed node exporter as systemctl daemon and smartmon in docker

/etc/systemd/system/node_exporter.service

```
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter --web.listen-address=:9500 --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target


```

```
  smartmon:
    image: ghcr.io/micha37-martins/smartmon:latest  # Pin to specific version in production
    container_name: smartmon
    network_mode: host
    privileged: true
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/nvme0
    volumes:
      - /var/lib/node_exporter/textfile_collector:/var/lib/node_exporter/textfile_collector
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```

and I see poor data in text file

 cat /var/lib/node_exporter/textfile_collector/smart_metrics.prom 


```
# HELP smartmon_smartctl_version SMART metric smartctl_version
# TYPE smartmon_smartctl_version gauge
smartmon_smartctl_version{version="7.4"} 1
# HELP smartmon_device_active SMART metric device_active
# TYPE smartmon_device_active gauge
smartmon_device_active{disk="/dev/sda",type="scsi"} 1
# HELP smartmon_device_info SMART metric device_info
# TYPE smartmon_device_info gauge
smartmon_device_info{disk="/dev/sda",type="scsi",model_family="",model_name="",device_model="",serial_number="S0M34ADA0000K501CJ7W",firmware_version="",vendor="",product="",revision="",lun_id=""} 1
# HELP smartmon_smart_support_available SMART metric smart_support_available
# TYPE smartmon_smart_support_available gauge
smartmon_smart_support_available{disk="/dev/sda",type="scsi"} 1
# HELP smartmon_smart_support_enabled SMART metric smart_support_enabled
# TYPE smartmon_smart_support_enabled gauge
smartmon_smart_support_enabled{disk="/dev/sda",type="scsi"} 1
# HELP smartmon_smartctl_run SMART metric smartctl_run
# TYPE smartmon_smartctl_run gauge
smartmon_smartctl_run{disk="/dev/sda",type="scsi"} 1766283600
```

```
smartctl --version
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-6.8.0-90-generic] (local build)

jq -V
jq-1.7

sudo /usr/sbin/smartctl --scan-open
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/sdb -d scsi # /dev/sdb, SCSI device
/dev/sdc -d scsi # /dev/sdc, SCSI device
/dev/nvme0 -d nvme # /dev/nvme0, NVMe device


sudo smartctl -i -j  /dev/sdb
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      4
    ],
    "pre_release": false,
    "svn_revision": "5530",
    "platform_info": "x86_64-linux-6.8.0-90-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-i",
      "-j",
      "/dev/sdb"
    ],
    "exit_status": 0
  },
  "local_time": {
    "time_t": 1766284517,
    "asctime": "Sun Dec 21 02:35:17 2025 UTC"
  },
  "device": {
    "name": "/dev/sdb",
    "info_name": "/dev/sdb",
    "type": "scsi",
    "protocol": "SCSI"
  },
  "scsi_vendor": "SEAGATE",
  "scsi_product": "ST600MM0006",
  "scsi_model_name": "SEAGATE ST600MM0006",
  "scsi_revision": "0001",
  "scsi_version": "SPC-4",
  "user_capacity": {
    "blocks": 1172123568,
    "bytes": 600127266816
  },
  "logical_block_size": 512,
  "scsi_lb_provisioning": {
    "name": "fully provisioned",
    "value": 0,
    "management_enabled": {
      "name": "LBPME",
      "value": 0
    },
    "read_zeros": {
      "name": "LBPRZ",
      "value": 0
    }
  },
  "rotation_rate": 10500,
  "form_factor": {
    "scsi_value": 3,
    "name": "2.5 inches"
  },
  "logical_unit_id": "0x5000c50076c269bf",
  "serial_number": "S0M3269G0000K4518MWG",
  "device_type": {
    "scsi_terminology": "Peripheral Device Type [PDT]",
    "scsi_value": 0,
    "name": "disk"
  },
  "scsi_transport_protocol": {
    "name": "SAS (SPL-4)",
    "value": 6
  },
  "smart_support": {
    "available": true,
    "enabled": true
  },
  "temperature_warning": {
    "enabled": true
  }
}

```

BUT with `-j` flag it shows temperature
```
sudo smartctl -a -j  /dev/sdb
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      4
    ],
    "pre_release": false,
    "svn_revision": "5530",
    "platform_info": "x86_64-linux-6.8.0-90-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-a",
      "-j",
      "/dev/sdb"
    ],
    "exit_status": 0
  },
  "local_time": {
    "time_t": 1766284696,
    "asctime": "Sun Dec 21 02:38:16 2025 UTC"
  },
  "device": {
    "name": "/dev/sdb",
    "info_name": "/dev/sdb",
    "type": "scsi",
    "protocol": "SCSI"
  },
  "scsi_vendor": "SEAGATE",
  "scsi_product": "ST600MM0006",
  "scsi_model_name": "SEAGATE ST600MM0006",
  "scsi_revision": "0001",
  "scsi_version": "SPC-4",
  "user_capacity": {
    "blocks": 1172123568,
    "bytes": 600127266816
  },
  "logical_block_size": 512,
  "scsi_lb_provisioning": {
    "name": "fully provisioned",
    "value": 0,
    "management_enabled": {
      "name": "LBPME",
      "value": 0
    },
    "read_zeros": {
      "name": "LBPRZ",
      "value": 0
    }
  },
  "rotation_rate": 10500,
  "form_factor": {
    "scsi_value": 3,
    "name": "2.5 inches"
  },
  "logical_unit_id": "0x5000c50076c269bf",
  "serial_number": "S0M3269G0000K4518MWG",
  "device_type": {
    "scsi_terminology": "Peripheral Device Type [PDT]",
    "scsi_value": 0,
    "name": "disk"
  },
  "scsi_transport_protocol": {
    "name": "SAS (SPL-4)",
    "value": 6
  },
  "smart_support": {
    "available": true,
    "enabled": true
  },
  "temperature_warning": {
    "enabled": true
  },
  "smart_status": {
    "passed": true
  },
  "temperature": {
    "current": 41,
    "drive_trip": 68
  },
  "power_on_time": {
    "hours": 61141,
    "minutes": 28
  },
  "scsi_start_stop_cycle_counter": {
    "year_of_manufacture": "20",
    "week_of_manufacture": "",
    "specified_cycle_count_over_device_lifetime": 10000,
    "accumulated_start_stop_cycles": 33,
    "specified_load_unload_count_over_device_lifetime": 300000,
    "accumulated_load_unload_cycles": 2576
  },
  "scsi_grown_defect_list": 0,
  "seagate_farm_log": {
    "supported": false
  },
  "scsi_error_counter_log": {
    "read": {
      "errors_corrected_by_eccfast": 846055609,
      "errors_corrected_by_eccdelayed": 0,
      "errors_corrected_by_rereads_rewrites": 0,
      "total_errors_corrected": 846055609,
      "correction_algorithm_invocations": 0,
      "gigabytes_processed": "1801.789",
      "total_uncorrected_errors": 0
    },
    "write": {
      "errors_corrected_by_eccfast": 0,
      "errors_corrected_by_eccdelayed": 0,
      "errors_corrected_by_rereads_rewrites": 0,
      "total_errors_corrected": 0,
      "correction_algorithm_invocations": 0,
      "gigabytes_processed": "9.945",
      "total_uncorrected_errors": 0
    }
  },
  "scsi_self_test_0": {
    "code": {
      "value": 2,
      "string": "Background long"
    },
    "result": {
      "value": 0,
      "string": "Completed"
    },
    "power_on_time": {
      "hours": 58820,
      "aka": "accumulated_power_on_hours"
    }
  },
  "scsi_self_test_1": {
    "code": {
      "value": 2,
      "string": "Background long"
    },
    "result": {
      "value": 2,
      "string": "Aborted (device reset ?)"
    },
    "power_on_time": {
      "hours": 56834,
      "aka": "accumulated_power_on_hours"
    }
  },
  "scsi_extended_self_test_seconds": 3777
}
```
